### ISSUE TITLE
Cannot download data needed for xgboost_customer_churn_neo.ipynb

### ISSUE THREAD

**Issue by sbhavani** [aws/amazon-sagemaker-examples#1950]
In this example:
https://github.com/aws/amazon-sagemaker-examples/blob/master/sagemaker_neo_compilation_jobs/xgboost_customer_churn/xgboost_customer_churn_neo.ipynb

When using SageMaker Studio and downloading the data from http://dataminingconsultant.com/DKD2e_data_sets.zip, it times out but downloading from a different location works. 

Looking at other issues, it might make sense to move all static assets referenced in notebooks to public S3 buckets.

**Comment by seanpmorgan** [comment]
Tested and this download works correctly now. While I agree it'd be great if we could host these in public s3 buckets, the problem is that it's difficult to track down the original source of datasets and determine if their license permits redistribution. If you identify any that look to be redistributable please let us know.

Closing as this is solved, but feel free to continue the discussion.

**Comment by prernakekre89** [comment]
hi @seanpmorgan , 

I am facing the same issue. my notebook instance is in Sydney. Please can you advice on what i can do? I am new to aws sagemaker 
![DataAccess_Connectionfail](https://user-images.githubusercontent.com/65585969/106424505-62d6c580-64b6-11eb-9348-aa41f37bce13.PNG)

**Comment by themd99** [comment]
> In this example:
> https://github.com/aws/amazon-sagemaker-examples/blob/master/sagemaker_neo_compilation_jobs/xgboost_customer_churn/xgboost_customer_churn_neo.ipynb
> 
> When using SageMaker Studio and downloading the data from http://dataminingconsultant.com/DKD2e_data_sets.zip, it times out but downloading from a different location works.
> 
> Looking at other issues, it might make sense to move all static assets referenced in notebooks to public S3 buckets.

Hello, can you share the other alternative locations.  It is still suspended for me and would like to progress with the course.  Someone mentioned Kaggle, but it is not the same data I believe.

Regards,
Aksel

**Comment by seanpmorgan** [comment]
> > In this example:
> > https://github.com/aws/amazon-sagemaker-examples/blob/master/sagemaker_neo_compilation_jobs/xgboost_customer_churn/xgboost_customer_churn_neo.ipynb
> > When using SageMaker Studio and downloading the data from http://dataminingconsultant.com/DKD2e_data_sets.zip, it times out but downloading from a different location works.
> > Looking at other issues, it might make sense to move all static assets referenced in notebooks to public S3 buckets.
> 
> Hello, can you share the other alternative locations. It is still suspended for me and would like to progress with the course. Someone mentioned Kaggle, but it is not the same data I believe.
> 
> Regards,
> Aksel

Hello, the notebooks have been updated with a synthetic dataset now.

**Comment by sylfree9999** [comment]
> > > In this example:
> > > https://github.com/aws/amazon-sagemaker-examples/blob/master/sagemaker_neo_compilation_jobs/xgboost_customer_churn/xgboost_customer_churn_neo.ipynb
> > > When using SageMaker Studio and downloading the data from http://dataminingconsultant.com/DKD2e_data_sets.zip, it times out but downloading from a different location works.
> > > Looking at other issues, it might make sense to move all static assets referenced in notebooks to public S3 buckets.
> > 
> > 
> > Hello, can you share the other alternative locations. It is still suspended for me and would like to progress with the course. Someone mentioned Kaggle, but it is not the same data I believe.
> > Regards,
> > Aksel
> 
> Hello, the notebooks have been updated with a synthetic dataset now.

Hi @seanpmorgan 
I still cannot download churn.txt using `aws s3 cp s3://sagemaker-sample-files/datasets/tabular/synthetic/churn.txt ./`
The problem is : fatal error: An error occurred (403) when calling the HeadObject operation: Forbidden

**Comment by seanpmorgan** [comment]
Hi @sylfree9999 I just tested this and successfully downloaded the dataset. The S3 bucket is public, make sure that your SageMaker Execution Role has access to S3
